# Site settings
title: King's Uncle
email: csdwz@outlook.com
description: "Nick liu blog."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kuncle.github.io/" # the base hostname & protocol for your site


# Social account
# twitter:  username
# weibo:    ID
github:   kuncle
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
